# Generated by Django 4.2.2 on 2024-04-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='commentary',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=150, verbose_name='ФИО'),
        ),
    ]
