# Generated by Django 4.2.2 on 2024-04-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_mailingattempt_mailing_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingAttempt',
            new_name='MailingLog',
        ),
    ]
