# Generated by Django 4.2.2 on 2024-04-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_alter_mailinglog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='last_success',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего отправления'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='server_response',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отклик почтового сервера'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.CharField(blank=True, default=False, max_length=15, null=True, verbose_name='Статус отправки'),
        ),
    ]
