# Generated by Django 4.2.2 on 2024-04-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_alter_mailinglog_last_success_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_set_is_active', 'Может отключать рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
